### PR TITLE
Use Ember.copy() for model.copy()

### PR DESCRIPTION
**Pull request by hperl**
This is a cherrypicked version (originally on edge) of PR #26, this time to the master branch.

This fixes issue #21.

### CODE REVIEW

**Comment by hperl** [comment]
@ghempton does this look good to you?

**Comment by ghempton** [comment]
Sorry for taking so long to merge this. I have been meaning to think through the implications of partially allowing for array/object attributes. I would like to support this, but want to make sure the implementation is robust. Particularly, what happens if you just modify a single element of the array? I would like for the adapter to handle dirty checking correctly in these cases.

**Comment by hperl** [comment]
No problem at all. Since `model.copy()` copies the whole array, if you modify a single element of the array, you have the original array in the client shadow and the modified array in the client model. For dirty checking, `model.diff()` should then pick up the differences.

Right now I think that since `model.diff()` just does a `!==` on the attributes, a "deep" attribute will always be marked as dirty. Probably, https://github.com/GroupTalent/epf/blob/master/lib/model/model.js#L110 should be `if(!Ember.isEqual(left, right))`, right?

**Comment by ghempton** [comment]
So the issue I can see is the case where the object has an array/object attribute and the user _only_ changes an item/property of this nested attribute. In this case, the model will never be flagged as dirty and won't be part of the flush (this is an optimization since we don't want to perform a `diff` on every model in the session).

The correct way to do this would be to proxy and/or add listeners to these complex attributes to flag the model as dirty when they are changed.

**Comment by hperl** [comment]
Right, as of now I just call `this.session.modelWillBecomeDirty(model)` before modifying the nested attribute. It'd be great if this wouldn't be nescessary any more.

**Comment by lastobelus** [comment]
I am trying to figure out a maintainable way to clone a record, and have it be live while it is being created server side, and tried model.copy unsuccessfully. Is this issue why? My clone should have the same belongs_to & be inserted into the same has_manys. Is there a generic way to do this?

**Comment by ghempton** [comment]
@lastobelus I think you should be able to simply call `model.copy` and then clear the id property, (e.g. model.set('id', null)). One other caveat is that `model.copy` creates lazy copies of relationships, so you will have to add it to a session in order for the relationships to load.

**Comment by ghempton** [comment]
This feature has been since added.

**Pull request closed without merging**
